spring:
  application:
    name: oauth-code-client

server:
  port: 18080

security:
  oauth2:
    client:
      client-id: client-id
      client-secret: client-secret
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token